name: qcd_env_test
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - pip
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiohttp=3.8.4
  - aiosignal=1.3.1
  - amply=0.1.6
  - appdirs=1.4.4
  - asttokens=2.4.1
  - async-timeout=4.0.3
  - atk-1.0=2.38.0
  - attrs=23.1.0
  - backports=1.1
  - backports.functools_lru_cache=1.6.4
  - bcrypt=3.2.2
  - boltons=23.0.0
  - brotli-python=1.1.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.0
  - ca-certificates=2023.11.17
  - cairo=1.16.0
  - certifi=2023.11.17
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - coin-or-cbc=2.10.10
  - coin-or-cgl=0.60.7
  - coin-or-clp=1.17.8
  - coin-or-osi=0.108.8
  - coin-or-utils=2.11.8
  - coincbc=2.10.10
  - colorama=0.4.6
  - comm=0.2.1
  - conda=23.7.4
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - configargparse=1.7
  - connection_pool=0.0.3
  - cryptography=40.0.2
  - datrie=0.8.2
  - debugpy=1.8.0
  - decorator=5.1.1
  - docutils=0.19
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - fftw=3.3.10
  - filelock=3.13.1
  - fmt=10.1.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.3.3
  - gdk-pixbuf=2.42.10
  - gettext=0.21.1
  - ghostscript=9.54.0
  - giflib=5.2.1
  - gitdb=4.0.11
  - gitpython=3.1.40
  - google-crc32c=1.5.0
  - graphite2=1.3.14
  - graphviz=7.1.0
  - grpcio=1.54.0
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=6.0.0
  - icu=72.1
  - idna=3.6
  - imagemagick=7.1.1_7
  - importlib_metadata=7.0.1
  - importlib_resources=5.12.0
  - ipykernel=6.28.0
  - ipython=8.19.0
  - jbig=2.1
  - jedi=0.19.1
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - jupyter_client=8.6.0
  - jupyter_core=5.3.0
  - keyutils=1.6.1
  - krb5=1.21.2
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libabseil=20230125.0
  - libarchive=3.6.2
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.4.0
  - libdeflate=1.18
  - libedit=3.1.20221030
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=12.2.0
  - libgd=2.3.3
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.1
  - libgomp=12.2.0
  - libgrpc=1.54.0
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libmamba=1.5.1
  - libmambapy=1.5.1
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=3.21.12
  - librsvg=2.54.4
  - libsodium=1.0.18
  - libsolv=0.7.25
  - libsqlite=3.40.0
  - libssh2=1.11.0
  - libstdcxx-ng=12.2.0
  - libtiff=4.5.0
  - libtool=2.4.7
  - libuuid=2.38.1
  - libwebp=1.3.0
  - libwebp-base=1.3.0
  - libxcb=1.13
  - libxml2=2.10.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.1
  - markupsafe=2.1.2
  - matplotlib-inline=0.1.6
  - multidict=6.0.4
  - nbformat=5.9.2
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - networkx=3.2
  - numpy=1.24.2
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.2
  - pandas=2.0.0
  - pango=1.50.14
  - parso=0.8.3
  - pcre2=10.40
  - perl=5.32.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - pluggy=1.3.0
  - prompt-toolkit=3.0.42
  - protobuf=4.21.12
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pulp=2.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.17.2
  - pygraphviz=1.10
  - pynacl=1.5.0
  - pyopenssl=23.2.0
  - pyparsing=3.1.1
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.10.10
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.16.3
  - python-tzdata=2023.3
  - python_abi=3.10
  - pytz=2023.3.post1
  - pyyaml=6.0
  - pyzmq=25.1.2
  - ratelimiter=1.2.0
  - re2=2023.02.02
  - readline=8.2
  - referencing=0.31.1
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - rpds-py=0.13.2
  - ruamel.yaml=0.17.40
  - ruamel.yaml.clib=0.2.7
  - setuptools=68.2.2
  - six=1.16.0
  - smart_open=6.3.0
  - smmap=5.0.0
  - snakemake-minimal=6.15.5
  - stack_data=0.6.2
  - stopit=1.1.2
  - tk=8.6.12
  - toolz=0.12.0
  - toposort=1.10
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.14.0
  - typing-extensions=4.5.0
  - typing_extensions=4.5.0
  - tzdata=2023c
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - wheel=0.42.0
  - wrapt=1.15.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-libxt=1.2.1
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.10
  - yaml=0.2.5
  - yaml-cpp=0.7.0
  - yarl=1.8.2
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.21.0
  - zstd=1.5.5